name: .NET

on: workflow_dispatch

jobs:
  publish:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: DotNet Bump Versions
      uses: SiqiLu/dotnet-bump-version@2.0.0
      with:
        version_files: "**/*.csproj"
        version_mask: 0.0.0.${{ github.run_number }}
        version_overwrite: "*.*.*.*"
    - name: publish
      run: dotnet publish App/BrowseRouter.csproj /p:PublishProfile=App/Properties/PublishProfiles/FolderProfile.pubxml
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: published-binary-${{ github.run_number }}
        path: |
          App/publish
          !App/publish/**/*.pdb
    - name: Test
      run: dotnet test --no-build --verbosity normal
